# Data preparation

scRNASequest pipeline is compatible with different single-cell experiment outputs, including the **10X MEX format** and the **10X h5 format** from cellranger. The user may need to manually separate the annotation file, so that no cell filtering was performed. In this chapter, we will walk through how to prepare the data before running the pipeline.

## Public data in h5 format

Here, we first present an example of the data processing steps using a public EMBL EBI dataset: [E-MTAB-11115](https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11115/){target="_blank"}. The nine processed zip files were downloaded and unzipped.

There are total 6 data, with 6 corresponding *raw_feature_bc_matrix.h5 files. These files are required by the pipeline:

```
#h5 matrix files
-rwxrwxr--. 1 zouyang ngs 165M Oct 25  2021 5705STDY8058280.raw_feature_bc_matrix.h5
-rwxrwxr--. 1 zouyang ngs 165M Oct 25  2021 5705STDY8058281.raw_feature_bc_matrix.h5
-rwxrwxr--. 1 zouyang ngs 156M Oct 25  2021 5705STDY8058282.raw_feature_bc_matrix.h5
-rwxrwxr--. 1 zouyang ngs 162M Oct 25  2021 5705STDY8058283.raw_feature_bc_matrix.h5
-rwxrwxr--. 1 zouyang ngs 149M Oct 25  2021 5705STDY8058284.raw_feature_bc_matrix.h5
-rwxrwxr--. 1 zouyang ngs 177M Oct 25  2021 5705STDY8058285.raw_feature_bc_matrix.h5
```

This dataset also has cell type annotation files associated with each data. These files are optional to the pipeline, but if you would like to use their cell type labels, it would be better to include them in the sample meta file (See section 5.2).

```
#Annotation files (optional to the pipeline)
-rwxrwx---. 1 zouyang ngs 440K Apr 21 16:59 5705STDY8058280.annotation.csv
-rwxrwx---. 1 zouyang ngs 446K Apr 21 16:59 5705STDY8058281.annotation.csv
-rwxrwx---. 1 zouyang ngs 310K Apr 21 16:59 5705STDY8058282.annotation.csv
-rwxrwx---. 1 zouyang ngs 282K Apr 21 16:59 5705STDY8058283.annotation.csv
-rwxrwx---. 1 zouyang ngs 157K Apr 21 16:59 5705STDY8058284.annotation.csv
-rwxrwx---. 1 zouyang ngs 555K Apr 21 16:59 5705STDY8058285.annotation.csv

#A brief look of the annotation file:
$ head -3 5705STDY8058280_annotation.csv
Cell.ID,sample,annotation_1,annotation_1_print
AAACCCAAGGAAGTAG-1,5705STDY8058280,Ext_L25,23_Ext_L25
AAACCCAAGGGCAGTT-1,5705STDY8058280,Ext_L56,24_Ext_L56
```

If **SampleName.metrics_summary.csv** files are available, please also add them in the same directory since the pipeline will use them to generate QC plots, but they are not required files of the pipeline. The expected file names should be:

```
5705STDY8058280.metrics_summary.csv
5705STDY8058281.metrics_summary.csv
5705STDY8058282.metrics_summary.csv
5705STDY8058283.metrics_summary.csv
5705STDY8058284.metrics_summary.csv
5705STDY8058285.metrics_summary.csv
```
**[Important]** Since we don't provide the path of these metrics_summary.csv files to the pipeline, their prefix **SampleName** must be consistent with the **Sample_Name** column in the sample meta file (See section 5.2), so that the pipeline can recognize them automatically. You can certainly rename the files and the corresponding **SampleName** column if you would like to change the data names and how they appear in the final results.

## Public data in 10X MEX format

Another popular format for single-cell RNA-seq is the [**MEX format**](https://kb.10xgenomics.com/hc/en-us/articles/115000794686-How-is-the-MEX-format-used-for-the-gene-barcode-matrices), with a **mtx file** and associated **barcodes** file as well as a **features** file. Here, we use a public dataset from NCBI/GEO: [GSE205483](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE205483) to walk through the procedures for pipeline setup.

There are total 4 data, and all the processed data can be downloaded from the Supplementary file section as a tar ball: GSE205483_RAW.tar:

```
#Untar the file
tar -xvf GSE205483_RAW.tar

$ ls -l

-rw-rw-r--. 1 ysun4 ysun4   4704844 Jun  2 15:13 GSM6213399_IT_YZ_0309_2904_barcodes.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4    260888 Jun  2 15:13 GSM6213399_IT_YZ_0309_2904_features.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4  64071180 Jun  2 15:13 GSM6213399_IT_YZ_0309_2904_matrix.mtx.gz
-rw-rw-r--. 1 ysun4 ysun4   5474445 Jun  2 15:21 GSM6213400_IT_YZ_0309_2905_barcodes.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4    260888 Jun  2 15:21 GSM6213400_IT_YZ_0309_2905_features.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4  73218924 Jun  2 15:21 GSM6213400_IT_YZ_0309_2905_matrix.mtx.gz
-rw-rw-r--. 1 ysun4 ysun4   4931566 Jun  2 15:30 GSM6213401_IT_YZ_0309_2908_barcodes.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4    260888 Jun  2 15:30 GSM6213401_IT_YZ_0309_2908_features.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4  53887060 Jun  2 15:30 GSM6213401_IT_YZ_0309_2908_matrix.mtx.gz
-rw-rw-r--. 1 ysun4 ysun4   4132528 Jun  2 15:37 GSM6213402_IT_YZ_0322_3125_barcodes.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4    260888 Jun  2 15:37 GSM6213402_IT_YZ_0322_3125_features.tsv.gz
-rw-rw-r--. 1 ysun4 ysun4  53205493 Jun  2 15:37 GSM6213402_IT_YZ_0322_3125_matrix.mtx.gz
```

Next, these files need to be organized into separate folders for the pipeline to read. In specific, we need to create separate folders for each data, and rename the three files to be: **barcodes.tsv.gz**, **features.tsv.gz**, and **matrix.mtx.gz**. The organized file hierarchy is below:

```
GSE205483/
    ├── GSM6213399_IT_YZ_0309_2904
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
    ├── GSM6213400_IT_YZ_0309_2905
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
    ├── GSM6213401_IT_YZ_0309_2908
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
    └── GSM6213402_IT_YZ_0322_3125
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
```

## Self-prepared files

If you have raw data in [FASTQ format](https://support.illumina.com/bulletins/2016/04/fastq-files-explained.html), please process them using the Cellranger pipeline to generate the raw_feature_bc_matrix.h5 and metrics_summary.csv files. Please visit [cellranger website here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count) for more details about the outputs. In short, cellranger outputs filtered_feature_bc_matrix.h5 (cells after filtering, recommended to use), raw_feature_bc_matrix.h5 (without filtering), and two folders for MEX format output: filtered_feature_bc_matrix, raw_feature_bc_matrix. Please organize the cellranger output files into the following file structures before running scRNASequest.

Below is the file hierarchy for h5 input files (metrics_summary.csv files are suggested to be included, but not required; If cell type classification annotation.csv files are available, it would be better to include them):

```
Project/
    ├── Data1.filtered_feature_bc_matrix.h5
    ├── Data1.annotation.csv                 (optional)
    ├── Data1.metrics_summary.csv            (optional)
    ├── Data2.filtered_feature_bc_matrix.h5
    ├── Data2.annotation.csv                 (optional)
    ├── Data2.metrics_summary.csv            (optional)
    ...
```

The file hierarchy for [MEX files](https://kb.10xgenomics.com/hc/en-us/articles/115000794686-How-is-the-MEX-format-used-for-the-gene-barcode-matrices):

```
Project/
    ├── Data1
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
    ├── Data2
        ├── barcodes.tsv.gz
        ├── features.tsv.gz
        └── matrix.mtx.gz
    ...
```
