#!/usr/bin/env bash


strIn=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scAnalyzer: Please run ./install to setup necessary env variables"
  exit
fi


if [[ -f "$strIn" ]]; then
  env -i strIn="$strIn" src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/external2h5ad.R $strIn 2>&1 | tee -a $(dirname $strIn)/sc2celldepot.$(date +%Y%m%d).log'
elif [[ -d "$strIn" ]]; then
  env -i strIn="$strIn" src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/external2h5ad.R $strIn 2>&1 | tee -a $(dirname $strIn)/sc2celldepot.$(date +%Y%m%d).log'
elif [[ ${#strIn} -gt 1 ]]; then
  echo "$strIn does NOT exist!"
else
  env -i src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/external2h5ad.R'
fi


