#!/usr/bin/env bash
#nohup scAnalyzer config.yml > QC.log 2>&1 &

config=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scAnalyzer: Please run ./install to setup necessary env variables"
  exit
fi

#condaEnv=$(head -n 1 $src/sys.yml)
#condaEnv=${condaEnv:1}
set -e
if [[ -f "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv >/dev/null 2>&1;python -u $src/scPipe.py $config 2>&1 | tee -a $config.$(date +%Y%m%d).log'
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv >/dev/null 2>&1;$src/../scReport $config 2>&1 | tee -a $config.$(date +%Y%m%d).log'
elif [[ -d "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv >/dev/null 2>&1;python -u $src/scPipe.py $config 2>&1 | tee -a $config/sc$(date +%Y%m%d).init.log'
else
  env -i src="$src" bash -c 'source $src/.env;eval $condaEnv >/dev/null 2>&1;python -u $src/scPipe.py'
fi
