#!/usr/bin/env bash
#nohup scPIPE config.yml > QC.log 2>&1 &

config=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scPIPE: Please run ./install to setup necessary env variables"
  exit
fi

#condaEnv=$(head -n 1 $src/sys.yml)
#condaEnv=${condaEnv:1}

env -i config="$config" src="$src" bash -c 'set -o allexport;source $src/.env;set +o allexport;eval $condaEnv;python -u $src/scPipe.py $config'

