#!/usr/bin/env bash

config=$1
src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scRef: Please run ./install to setup necessary env variables"
  exit
fi

if [[ -f "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/scRef.R $config 2>&1 | tee -a $config.$(date +%Y%m%d).log'
elif [[ -d "$config" ]]; then
  env -i config="$config" src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/scRef.R $config 2>&1 | tee -a $config/init_$(date +%Y%m%d).log'
else
  env -i src="$src" bash -c 'source $src/.env;eval $condaEnv;Rscript $src/scRef.R'
fi
