#!/usr/bin/env bash
#nohup scRMambient meta.csv > QC.log 2>&1 &

src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scRMambient: Please run ./install to setup necessary env variables"
  exit
fi

## parse the input arguments
meta=$1
shift
nCore=0
POSITIONAL=()
parallel='T'
while [[ $# -gt 0 ]]
do
key=$1
case $key in
    -t|--thread)
    nCore="$2"
    shift # past argument
    shift # past value
    ;;
    -n|--nocluster)
    parallel="F"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

set -e
if [[ -f "$meta" ]]; then
  env -i meta="$meta" nCore=$nCore parallel=$parallel src="$src" bash -c 'source $src/.env;eval $condaEnv;export LD_LIBRARY_PATH=/gpfs/data01/glasslab/bioinformatics/condaEnv/scRNAsequest/lib;python -u $src/scRMambient.py $meta $nCore $parallel 2>&1 | tee -a scRMambient.$(date +%Y%m%d).log'
else
  echo "scRMambient: Remove background RNA"
  echo "https://cellbender.readthedocs.io/en/latest/usage/index.html"
  echo "Please provide the sample sheet contains raw expression h5 file path, expected cell number and droplet number (includes some empty ones)"
  echo "Usage: scRMambient <sample meta csv> [-t 4] [-n]"
  echo "-t: (option) the number of CPU threats cores [default GPU]"
  echo "-n: (option) if set No SGE/Slurm set up, will use local CPUs [default Not set]"
fi
