#!/usr/bin/env bash

src="$(dirname $0)/src"

if [[ ! -f "$src/.env" ]]; then
  echo "scAnalyzer: Please run ./install to setup necessary env variables"
  exit
fi

tool="${1:- -h}"
strH5ad="${2:-''}"
addi="${3:-''}"

if [[ -w ./ ]]; then
  env -i src="$src" tool="$tool" strH5ad="$strH5ad" addi="$addi" bash -c 'source $src/.env;eval $condaEnv;python -u $src/scTool.py $tool "$strH5ad" "$addi"'
else
  echo "Error: No written permission in $(readlink -e .)"
fi




