```{r, echo=FALSE}

#Retrieve information from the previously saved bookdown.info.txt file
PWD <- system("pwd", intern = TRUE)
Info <- paste0(PWD, "/bookdown.info.txt")
Data <- read.table(Info)
Source_code <- Data$V2[1]
Working_dir <- Data$V2[2]
Config_file <- Data$V2[3]

#Extract information from the Config_file
config <- sapply(yaml::read_yaml(Config_file),unlist)
ProjectName <- config$prj_name
```

---
title: Bookdown report of `r ProjectName`
date: "Generated on `r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction {-}

This is a summary report generated by scReport (part of [scRNASequest pipeline](https://interactivereport.github.io/scRNAsequest/tutorial/docs/index.html)) using [Bookdown](https://bookdown.org/).

This report contains basic QC plots generated by the pipeline. If you turn on the filter_step when running [scAnalyzer](https://interactivereport.github.io/scRNAsequest/tutorial/docs/running-the-pipeline.html#scanalyzer), this report will also display QC plots before and after filtering.

Please go through the figures carefully and decide the cutoffs for data filtering.

### Project Overview {-}

Here is a brief overview of the project and filtering criteria:

- Project Name: **`r config$prj_name`**

- Project Title: **`r config$prj_title`**

- Filtering Option: **`r config$filter_step`**

- Filtering Mitochondria: **`r config$gene_group[5]`**

- Filtering min.cells: **`r config$min.cells`**

- Filtering min.features: **`r config$min.features`**

- Filtering highCount.cutoff: **`r config$highCount.cutoff`**

- Filtering highGene.cutoff: **`r config$highGene.cutoff`**

For more details, please check the config.yml file and related config.yml.*.log file:

- **`r Config_file`**